name: Deploy static content to website-develop

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages-dev'
  cancel-in-progress: true

jobs:
  format:
    name: JS Code Format
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
        with:
          path: pycon-website
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '25.2'
      - name: Install node dependencies
        run: |
          cd pycon-website/
          npm install
      - name: Show node environment
        run: |
          node --version
          npm --version
      - name: Run JS lint
        run: |
          cd pycon-website/
          npm run lint-only

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '25.2'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-artifact
          path: dist/

  deploy:
    if: github.event_name == 'push'
    name: Deploy to Develop
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate access token
        if: always()
        id: generate_access_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PYCON_CO_APP_ID }}
          private-key: ${{ secrets.PYCON_CO_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: PyConColombia/website-develop
          token: ${{ steps.generate_access_token.outputs.token }}
          path: website-develop
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist-artifact
          path: dist
      - name: Prepare deployment
        run: |
          find website-develop/ -mindepth 1 ! -name 'CNAME' ! -path "website-develop/.git*" -delete
          mv dist/* website-develop/
      - name: Commit and push changes
        run: |
          cd website-develop
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Deploy: $(date +'%Y-%m-%d %H:%M:%S') to branch ${{ github.ref_name }}"
            git push origin gh-pages
          else
            echo "No changes to commit. Skipping deployment."
          fi
